// Code generated by "gonacos_config --embed=GlobalConfig --config=Other:other_config.OtherConfig --dataid=other_config --codec=yaml"; DO NOT EDIT.
package config

import "fmt"
import gonacos "github.com/reatang/go-simple-nacos"
import "github.com/reatang/go-simple-nacos/tests/config/other_config"
import "sync"

var __GlobalConfigOtherMutex = sync.RWMutex{}

func RegisterEmbedGlobalConfigOther(ncc *gonacos.NacosConfigClient, c *other_config.OtherConfig) {
	ncc.WatchF("", "other_config", func(namespace, group, dataId, data string) {
		__GlobalConfigOtherMutex.Lock()
		defer __GlobalConfigOtherMutex.Unlock()

		err := gonacos.DecodeYaml(data, &c)
		if err != nil {
			fmt.Println("[gonacos]dataid:other_config,error:", err.Error())
		}
	})
}

func (c *GlobalConfig) GetOther() other_config.OtherConfig {
	__GlobalConfigOtherMutex.RLock()
	defer __GlobalConfigOtherMutex.RUnlock()

	return c.Other
}
